### ISSUE TITLE
Example file corresponding the vignette

### ISSUE THREAD

**Issue by tduigou** [PlantSynBioLab/AssemblyTron#3]
Hi,

I am giving a try to your app, it sounds promising, but I have a couple of questions:
- Is it compatible with Linux and MacOS?
- Following the vignette (https://plantsynbiolab.github.io/AssemblyTron-vignette/), I am stuck a the step of the golden gate assembly (`This vignette will go through the workflow of option five, which is a Golden Gate assembly with 96 possible primers and templates...`). Where can I find the files to provide?

Thanks,
Best wishes,
Thomas

**Comment by tduigou** [comment]
An additional question: is it possible to use another format than the j5 as input? For instance a set of CSV files or SVOL files provided by the user?

Thanks,
Best wishes,
Thomas

**Comment by jbryantvt** [comment]
Hi Thomas,
Thanks for trying out AssemblyTron!

- The AssemblyTron workflow should work on Linux and MacOS. The only part that might cause some trouble is the [Copy Cloning.bat](https://github.com/PlantSynBioLab/AssemblyTron/blob/master/src/AssemblyTron/Copy%20Cloning.bat) script. We include a [Copy_Cloning.sh](https://github.com/PlantSynBioLab/AssemblyTron/src/AssemblyTron/Copy_Cloning.sh) script in the src folder as well, but it has not been thoroughly tested since our OT-2 is connected to a PC. I would recommend working with your IT supervisor to get the Copy Cloning script set up for reasons listed in the vignette.


- For this step that you're stuck on, the tkinter pop-up window is to navigate to the folder containing your j5 combinatorial design file. You can store this design file in any folder on your computer. [The design file we use in our manuscript is attached here for reference.](https://github.com/PlantSynBioLab/AssemblyTron/files/9874088/pmas00001_combinatorial.csv)

- For now AssemblyTron only accepts j5 combinatorial design files as input. However, if you send me the input files that you typically work with, we will begin developing a new feature to support your input files.

Thanks so much for your inquiry, and let me know if you have any more questions!

John

**Comment by tduigou** [comment]
Hi @jbryantvt,

Thanks for the input file. Looking at it, I saw the last section. Is it this part that defined the final constructs?
```
"Combinations of Assembly Pieces"
Variant,,,"Bin 0",,"Bin 1",,"Bin 2",,"Bin 3"
Number,Name,"Assembly Method",Part(s),"Assembly Piece ID Number",Part(s),"Assembly Piece ID Number",Part(s),"Assembly Piece ID Number",Part(s),"Assembly Piece ID Number"
0,pmas00001,Golden-gate,(backbone),0,(Yukon),1,(bb2),2,(AmpR),3
1,pmas00002,Golden-gate,(backbone),0,(fuGFP),4,(bb2),2,(AmpR),3
2,pmas00003,Golden-gate,(backbone),0,(tsPurple),5,(bb2),2,(AmpR),3
3,pmas00004,Golden-gate,(backbone),0,(eforCP),6,(bb2),2,(AmpR),3
```

Is it possible to use part of the AssemblyTron just providing such information as a CSV file? This would open up the use of AssemblyTron to other use cases, where the j5 is not used.


Following the execution of the vignette, I met path issues (when looking for `paths.csv`):
```
$ python -m AssemblyTron.Golden_Gate.Setup_nodigests_seppcr_gradient_96  

Traceback (most recent call last):
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tduigou/code/AssemblyTron/src/AssemblyTron/Golden_Gate/Setup_nodigests_seppcr_gradient_96.py", line 87, in <module>
    paths = pandas.read_csv(walk_up_folder(os.getcwd(), 2)+'\paths.csv')
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tduigou/code\\paths.csv'
```

It looks there is potentially two issues, (i) is that the way the path is encoded is made for Windows (with the `\` instead of the `/`), and (ii) it expects the `paths.csv` file to be at a specific location relatively to the working directory (ie assuming `paths.csv` is at the root of `AssemblyTron` the code should be executed from `AssemblyTron/src`).

I fixed that in the code, but I went into another issue:
```
$ python -m AssemblyTron.Golden_Gate.Setup_nodigests_seppcr_gradient_96

Traceback (most recent call last):
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tduigou/code/AssemblyTron/src/AssemblyTron/Golden_Gate/Setup_nodigests_seppcr_gradient_96.py", line 92, in <module>
    shutil.copy2(paths.loc[0].at['opentrons_repo']+'/j5_to_csvs.R', name)
NameError: name 'name' is not defined
```

Best wishes,
Thomas

**Comment by jbryantvt** [comment]
Hi Thomas,

1. If you wanted to bypass the primer/template dilution, PCR mix, and DpnI digest steps and provide a manually generated combinations.csv file, then you can specify that you only want to run Golden Gate Setup and the Golden Gate run in a tkinter pop-up window further downstream in the setup process. The protocol would then just mix together fragments and run the Golden Gate assembly in the thermocycler. The locations of the assembly fragments are determined during the PCR steps, so this modification would probably require some additional code development. What other use cases do you have in mind?
2. Did you run the pathswriter.py script in your AssemblyTron working directory (`AssemblyTron/src/AssemblyTron`)? The command would be: `! python -m AssemblyTron.pathswriter`. It does need to be executed from the working directory, so I will update the vignette to reflect this.
3. `name` is a string variable containing the path to the folder containing your combinatorial design CSV. It is specified when the tkinter window that says to "Navigate to your j5 design file" pops up. Perhaps you didn't navigate to the folder where your design file is stored? I can't think of another reason why the string variable wouldn't be defined.

**Comment by tduigou** [comment]
Hi @jbryantvt,

1. We were thinking about users providing the parts already designed, and providing a combination to be build with a combinations.csv file, as you described. 

2. I ran the command `! python -m AssemblyTron.pathswriter` form the folder `AssemblyTron/src/AssemblyTron`, which update the `paths.csv` file at `AssemblyTron/src/AssemblyTron/paths.csv`. I have still the path issue appearing if I don't edit the code (file paths.csv not found).

3. I have a different error now. I executed the code from the `AssemblyTron/src/AssemblyTron` and put the j5 file you provided at `AssemblyTron/j5-input`. I am using Mac OS (since there is no `Rscript.exe` on MacOS, I added a link using `ln Rscript Rscript.exe`): 
```
$ python -m AssemblyTron.Golden_Gate.Setup_nodigests_seppcr_gradient_96
/Users/tduigou/code/AssemblyTron/j5-input
Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --slave --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R
Traceback (most recent call last):
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tduigou/code/AssemblyTron/src/AssemblyTron/Golden_Gate/Setup_nodigests_seppcr_gradient_96.py", line 103, in <module>
    shutil.copy2(name+'/assembly.csv', paths.loc[0].at['opentrons_repo']+'/Golden_Gate/')
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/tduigou/anaconda3/envs/assembly-tron/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tduigou/code/AssemblyTron/j5-input/assembly.csv'
```
